# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Automation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE }}
        ports:
          - 5432:5432
    env:
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}
      DIALECT: ${{ secrets.DIALECT }}

    steps:
      - name: create env file
        run: |
          touch .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DATABASE=${{ secrets.DATABASE }} >> .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo DIALECT=${{ secrets.DIALECT }} >> .env

      - uses: actions/checkout@v3
        name: Use Node.js ${{ matrix.node-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm test